title: Harry Gibson 
logo: "/images/harry_gibson_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Geospatial Data Archive Developer </strong>
  <br><br>
  (profile)
  <br><br>
  <a href="https://www.linkedin.com/in/harry-gibson-b1854924/" target="_blank">LinkedIn Profile</a> | 
  <a href="https://www.researchgate.net/profile/Harry_Gibson2" target="_blank">ResearchGate</a>
  
theme: jekyll-theme-leap-day
google_analytics: UA-153224943-1 # your Google Analytics tracking ID here
include: ['_pages']